from .base_parser import BaseParser
from .catchall.default_catchall import DefaultCatchallParser
from .collection.artblocks import ArtblocksParser
from .collection.autoglyphs import AutoglyphsParser
from .collection.chainrunners import ChainRunnersParser
from .collection.collection_parser import CollectionParser
from .collection.decentraland import DecentralandParser
from .collection.ens import ENSParser
from .collection.foundation import FoundationParser
from .collection.hashmasks import HashmasksParser
from .collection.loot import LootParser
from .collection.makersplace import MakersPlaceParser
from .collection.nouns import NounsParser
from .collection.punks import PunksParser
from .collection.superrare import SuperRareParser
from .collection.zora import ZoraParser
from .schema.opensea import OpenseaParser
from .schema.schema_parser import SchemaParser
