name: Application CI/CD

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      py_modified: ${{ steps.filter.outputs.py_modified }}
      py_modified_files: ${{ steps.filter.outputs.py_modified_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            py_modified:
              - added|modified: "./**/*.py"

  pytest:
    needs: changes
    if: ${{ needs.changes.outputs.py_modified == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: run
        run: |
          poetry run python -m pytest tests

  flake8:
    needs: changes
    if: ${{ needs.changes.outputs.py_modified == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: run
        run: |
          poetry run flake8 ${{ needs.changes.outputs.py_modified_files }}
